export type Role = 'administrator' | 'rahbar' | 'xodim'
export interface User { id: string; username: string; full_name: string; role: Role; is_active: boolean; created_at: string; last_login_at?:string|null }
export interface Source { citation_number?: number; document_id: string; document_name: string; article_or_clause?: string; display_label?:string; url: string; excerpt: string; full_excerpt?:string; page?: number; section?:string; evidence_type?:'nhh'|'document' }
export interface AiResult { history_id: string; answer: string; sources: Source[]; export_url?: string; official_export_url?:string; internal_evidence_url?:string; export_missing_fields?:string[]; result_kind: 'ok'|'source_matches'|'corpus_empty'|'no_sources'; warning?:string; effective_mode:'legal'|'general'; routed_to_legal:boolean; evidence_context?:'legal'|'document'|'draft'|'analytics'|'general'; structured?:Record<string,unknown> }
export type LlmProviderState = 'not_configured'|'unreachable'|'unauthorized'|'model_missing'|'ready'
export interface LlmProviderStatus { name:string; label:string; role:'primary'|'fallback'; state:LlmProviderState; model?:string|null; detail:string; reachable:boolean; model_loaded:boolean }
export interface SystemStatus { api:'ready'; embedding_state:'idle'|'loading'|'ready'|'error'; embedding_message:string; embedding_model:string; llm_provider:string; llm_fallback_enabled:boolean; llm_configured:boolean; llm_active_model?:string|null; llm_providers:LlmProviderStatus[]; groq_key_configured:boolean; groq_model_configured:boolean; groq_active_model?:string|null; groq_models_configured?:number; active_nhh_documents:number; nhh_chunks:number; accessible_documents:number; database_state?:'ready'|'error'; failed_nhh_documents:number; pending_nhh_documents:number }
export interface AiReadiness { legal_ready:boolean; general_ready:boolean; status:'ready'|'preparing'|'unavailable'; message:string }
export interface Doc { id: string; owner_id: string; filename: string; media_type: string; size_bytes: number; category: string; is_confidential: boolean; created_at: string }
export interface Nhh { id: string; title: string; category: string; source_url?: string; official_number?:string|null; adoption_date?:string|null; original_filename: string; indexed: boolean; is_active: boolean; updated_at: string; extraction_status:string; indexing_status:string; processing_error?:string|null; uploaded_at:string; indexed_at?:string|null; chunk_count:number }
export type TaskStatus = 'yangi'|'jarayonda'|'bajarildi'|'bekor_qilindi'
export type TaskPriority = 'past'|'odatiy'|'yuqori'|'shoshilinch'
export interface Task { id: string; title: string; description: string; assigned_to: string; created_by:string; assignee_name?:string; creator_name?:string; status: TaskStatus; priority:TaskPriority; deadline: string; created_at:string; updated_at:string; completed_at?:string|null; related_document_id?:string|null; is_overdue: boolean }
export interface TaskEvent { id:string; task_id:string; actor_id?:string|null; event_type:string; message:string; changes:Record<string,unknown>; created_at:string }
export interface OrganizationProfile { id:string; organization_name:string; organization_name_secondary:string; short_name:string; parent_organization:string; address:string; phone:string; email:string; website:string; tax_id:string; outgoing_prefix:string; department:string; letterhead_text:string; footer_text:string; signatory_name:string; signatory_title:string; qr_verification_url:string; barcode_text:string; logo_stored_name?:string|null; updated_at:string }
export interface History { id: string; user_id: string; operation: string; request_text: string; response_text: string; status:'success'|'fallback'|'failure'; sources: Source[]; created_at: string }
